export type CsvRow = {
  送信日時?: string;
  "貸出・返却場所"?: string;
  "ご契約者様　氏名"?: string;
  "ご契約者様　氏名_カナ"?: string;
  メールアドレス?: string;
  携帯電話番号?: string;
  "住所：郵便番号"?: string;
  "住所：都道府県"?: string;
  "住所：市区町村"?: string;
  "住所：番地"?: string;
  "住所：マンション・ビル名"?: string;
  生年月日?: string;
  ご乗車予定人数?: string;
  貸出希望日?: string;
  貸出時間?: string;
  返却希望日?: string;
  返却時間?: string;
  希望車種?: string;
  割引プラン?: string;
  "安心補償サービス　2,200円/日（税込）"?: string;
  "チャイルドシート　550円/日（税込）"?: string;
  "ジュニアシート　550円/日（税込）"?: string;
  "ワンタッチタープ　1,100円/日（税込）"?: string;
  "テーブル・イスセット　550円/日（税込）"?: string;
  マイカーお預かりサービス?: string;
  その他ご要望?: string;
  ご確認?: string;
};

export type Reservation = {
  id: string;
  submittedAt: string;
  pickupReturnPlace: string;
  name: string;
  nameKana: string;
  email: string;
  phone: string;
  postalCode: string;
  prefecture: string;
  city: string;
  address1: string;
  building: string;
  pickupDate: string;
  pickupTime: string;
  returnDate: string;
  returnTime: string;
  carType: string;
  passengerCount: string;
  discountPlan: string;
  insurance: boolean;
  childSeatCount: number;
  juniorSeatCount: number;
  tarpCount: number;
  tableSetCount: number;
  myCarParking: string;
  note: string;
};
